desired_data:
  - nuplan_test

cache_location: "/dir/to/trajdata/cache" # Trajdata cache location

incl_vector_map: true
rebuild_cache: false
rebuild_maps: false
require_map_cache: false
num_workers: 1
desired_dt: 0.5
verbose: true

data_dirs:
  nuplan_test: "/dir/to/nuplan-v1.1" # nuplan-v1.1

# scene_indices: [0]

