# @package _global_

defaults:
  - /stable_manifest/oss  # Add oss for images that need to be built
  - /eval/eval_in_separate_job  # Include eval service definition
  - _self_  # Override the GPUs to null

defines:
  # The repo-relative resolver makes the path relative to the git repo root.
  filesystem: ${repo-relative:"data"}


services:
  driver:
    replicas_per_container: 1
    gpus: null

  sensorsim:
    replicas_per_container: 1
    gpus: null

  physics:
    replicas_per_container: 1
    gpus: null

  trafficsim:
    replicas_per_container: 1
    gpus: null

  controller:
    replicas_per_container: 1
    gpus: null

  eval:
    replicas_per_container: 1
    gpus: null


wizard:
  run_method: "NONE"
  dry_run: true
  validate_mount_points: false
  log_dir: "./generated_configs"
  # Include eval in the services list so they get added to docker-compose.yaml
  run_eval_services: ["eval"]

scenes:
  scene_ids: []
